name: BACKEND-DEV-CD

on:
  push:
    branches:
      - develop-backend
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: self-hosted
  steps:
    - name: 수정 권한 부여
      run: |
        sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2023-trip-draw

    - name: 체크아웃
      uses: actions/checkout@v3

    - name: 빌드
      run: |
        chmod +x ./gradlew
        ./gradlew bootjar

    - name: 배포된 프로그램 종료
      run: |
        if sudo lsof -i :8080; then
          sudo lsof -i :8080 | awk 'NR!=1 {print $2}' | sudo xargs kill -9
        fi

    - name: 배포
      run: |
        sudo  nohup java -jar build/libs/tripdraw.jar &
