spring:
  config:
    active:
      on-profile: test

  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8://test
    username: root
    password: test

  task:
    execution:
      pool:
        core-size: 8
        queue-capacity: 100
        max-size: 16

  jpa:
    show_sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        highlight_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: create-drop


  flyway:
    url: jdbc:tc:mysql:8://test
    user: root
    password: test
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration

cloud:
  aws:
    s3:
      bucket: 2023-team-project
    stack:
      auto: false
    credentials:
      instanceProfile: true

jwt:
  access:
    secret-key: tripdraw1herbchangerhuchureootterpinguboarweareoneteamoneforallallforone710pleasegivemeahighsalaryjob
    expiration-time: 1800000  # 30 minutes
  refresh:
    secret-key: weareoneteamoneforallallforone710pleasegivemeahighsalaryjobtripdraw1herbchangerhuchureootterpinguboar
    expiration-time: 1209600000  # 14 days

trip:
  domain:
  base:
  post:
  route:

oauth:
  kakao:
    info-url: https://kapi.kakao.com/v2/user/me

file:
  common:
    domain: https://image.tripdraw.site
    root: 2023-tripdraw/prod/
  post:
    directory: post/
  route:
    directory: route/
