spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8://test
    username: root
    password: test

  task:
    execution:
      pool:
        core-size: 8
        queue-capacity: 100
        max-size: 16

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: true
    baselineOnMigrate: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /**

trip:
  domain:
  base:
  post:
  route:

jwt:
  access:
    secret-key: ACCESSTOKENACCESSTOKENACCESSTOKENACCESSTOKENACCESSTOKENACCESSTOKENACCESSTOKENACCESSTOKEN
    expiration-time: 1800000  # 30 minutes
  refresh:
    secret-key: REFRESHTOKENREFRESHTOKENREFRESHTOKENREFRESHTOKENREFRESHTOKENREFRESHTOKENREFRESHTOKENREFR
    expiration-time: 1209600000  # 14 days

oauth:
  kakao:
    info-url: https://kapi.kakao.com/v2/user/me
