name: BACKEND-DEV-CD

on:
  push:
    branches:
      - develop-backend

jobs:
  deploy:
    runs-on: self-hosted
    env:
      working-directory: /home/ubuntu

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: 배포 스크립트 실행
        run: |
          sh deploy.sh
        working-directory: ${{ env.working-directory }}
