name: BACKEND-DEV-CD

on:
  push:
    branches:
      - develop-backend

jobs:
  deploy:
    runs-on: backend-dev-cd

    steps:
      - name: 배포 스크립트 실행
        run: |
          cd
          sudo sh deploy.sh
        working-directory: ${{ env.working-directory }}

      - name: 슬랙 알림 발송
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo.message,commit,author,action,workflow
          mention: here
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
