name: BACKEND-PROD-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: backend-prod-cd

    steps:
      - name: 서브 모듈 checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TRIP_DRAW_TOKEN }}
          submodules: recursive

      - name: 배포 스크립트 실행
        run: |
          cd
          sudo sh deploy.sh
        working-directory: ${{ env.working-directory }}
